server:
  port: 8080
spring:
  application:
    name: consumer-user
  redis:
    jedis:
      pool:
        max-active: 5000 #最大连接数
        max-idle: 30     #最大空闲连接数
        min-idle: 5      #最小空闲连接数
        max-wait: 3000   #获取连接最大等待时间 ms  #default -1
    timeout: 10000
    cluster-nodes: 192.168.0.106:7301,192.168.0.106:7302,192.168.0.106:7303,192.168.0.106:7304,192.168.0.106:7305,192.168.0.106:7306
#    password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://server1.com:8001/eureka/
#      defaultZone: http://server1.com:8001/eureka/,http://server2.com:8002/eureka/,http://server3.com:8003/eureka/