server:
  port: 8003
spring:
  application:
    name: Euraka-Node3
  profiles:
    active: server3
  security:
    user:
      name: admin
      password: admin123
eureka:
  instance:
    hostname: server3.com
  client:
    service-url:
      defaultZone: http://admin:admin123@server1.com:8001/eureka/,http://admin:admin123@server2.com:8002/eureka/
    fetch-registry: false
    register-with-eureka: false