server:
  port: 7889
  undertow:
    direct-buffers: true
    io-threads: 4
    worker-threads: 160
spring:
  application:
    name: service-stream-provider
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092  #Kafka的消息中间件服务器
          zk-nodes: localhost:2181 #Zookeeper的节点，如果集群，后面加,号分隔
          auto-create-topics: true #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了
      #这里用stream给我们提供的默认output，后面会讲到自定义output
      bindings:
        #自定义output
        example-topic:
          #消息发往的目的地
          destination: topic-linzi
          #消息发送的格式，接收端不用指定格式，但是发送端要
          content-type: application/json #text/plain
          #只要把这些应用放置于同一个 “group” 中，就能够保证消息只会被其中一个应用消费一次
          group: group-linzi               #分组的组名
#同一个topic下多个消费者应用使用group，组名可以不同并且多个，但是消费数据只会被其中某一个消费者应用消费一次
eureka:
  client:
    serviceUrl:
      defaultZone: http://server1.com:8001/eureka/